version: '3.5'
services:
  mockserver:
    build: mockserver
    ports: ['8001:8000']
    volumes:
      - './mockserver/public:/home/public'
      - './mockserver/server.py:/home/server.py'
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      cache_from:
        - eu.gcr.io/tmrow-152415/electricitymap_web:production
        - eu.gcr.io/tmrow-152415/electricitymap_web:staging
        - eu.gcr.io/tmrow-152415/electricitymap_web:latest
    image: eu.gcr.io/tmrow-152415/electricitymap_web:latest
    command: npm run server-dev
    environment:
      - NODE_ENV=development
    ports: ['8000:8000']
    volumes:
      - './web/server.js:/home/src/electricitymap/contrib/web/server.js'