version: 2
jobs:
  verify_python:
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - restore_cache:
          key: venv-{{ checksum "poetry.lock" }}
      - run:
          name: Upgrade pip
          command: sudo pip install -q --upgrade pip
      - run:
          name: Install dependencies
          command: |
            set -eux -o pipefail
            sudo apt-get install libxml2-dev tesseract-ocr tesseract-ocr-eng
            poetry install -E parsers
      - run:
          name: Verify changes
          command: |
            set -eux -o pipefail
            poetry run lint
            poetry run test
      - save_cache:
          key: venv-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"

  lint_json:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - run:
          command: |
            sudo npm install -g jsonlint-mod
            jsonlint config/*.json web/locales/*.json

  test_js:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - run:
          command: |
            sudo npm install -g jest
            jest

  lint_js:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
      - run:
          command: |
            set -eux -o pipefail
            pushd web
            yarn
            yarn lint
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
          paths:
            - "web/node_modules"

workflows:
  version: 2
  all:
    jobs:
      - verify_python
      - lint_js
      - lint_json
      - test_js
