version: 2.1

executors:
  js-exec:
    docker:
      - image: node:12.22

commands:
  fast-checkout:
    steps:
      - run: git clone --depth 1 https://github.com/tmrowco/electricitymap-contrib.git --branch "$CIRCLE_BRANCH" .

jobs:
  verify_python:
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - restore_cache:
          key: venv-{{ checksum "poetry.lock" }}
      - run:
          name: Upgrade pip
          command: sudo pip install -q --upgrade pip
      - run:
          name: Install dependencies
          command: |
            set -eux -o pipefail
            sudo apt-get install libxml2-dev tesseract-ocr tesseract-ocr-eng
            poetry install -E parsers
      - run:
          name: Verify changes
          command: |
            set -eux -o pipefail
            poetry run lint
            poetry run test
      - save_cache:
          key: venv-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"

  lint_json:
    executor: js-exec
    steps:
      - fast-checkout
      - run:
          command: |
            npm install -g jsonlint-mod
            jsonlint -q config/*.json web/locales/*.json

  test_js:
    executor: js-exec
    steps:
      - fast-checkout
      - run:
          command: |
            npm install -g jest
            jest

  lint_js:
    executor: js-exec
    steps:
      - fast-checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
      - run:
          command: |
            set -eux -o pipefail
            cd web
            yarn
            yarn lint --quiet
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
          paths:
            - "web/node_modules"

  build_test:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - fast-checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
      - run:
          name: Build
          command: |
            set -euo pipefail
            time docker-compose build mockserver
            time docker-compose build web
            # Make sure files are available outside of container
            CONTAINER_ID=$(docker create eu.gcr.io/tmrow-152415/electricitymap_web:latest)
            docker cp $CONTAINER_ID:/home/src/electricitymap/contrib/web/public/dist web/public/dist
          no_output_timeout: 30m
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "web/yarn.lock" }}
          paths:
            - "web/node_modules"

workflows:
  version: 2
  all:
    jobs:
      - verify_python
      - lint_js
      - lint_json
      - test_js
      - build_test:
          requires:
            - lint_js
            - verify_python
            - lint_json
            - test_js
