version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-if-app-should-build
          mapping: |
             (web|mobileapp)/.* build-app true
          #base-revision: main
          config-path: .circleci/continue_config.yml