version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.1

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          tag: '3.8.12'
          name: check-if-app-should-build
          mapping: |
             (web|mobileapp)/.* build-app true
          base-revision: master
          config-path: .circleci/continue_conf.yml