bounding_box:
  - - 19.3044861183
    - 39.624997667
  - - 21.0200403175
    - 42.6882473822
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: null
  biomass:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: 1
  coal:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: null
  gas:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: 98
  geothermal:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: null
  hydro:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: 2484
  hydro storage:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: null
  oil:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: null
  solar:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: 23
  unknown:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: null
  wind:
    datetime: '2023-01-01'
    source: entsoe.eu
    value: null
contributors:
  - corradio
  - nessie2013
  - autipial
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionCapacity: ENTSOE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: Europe/Tirane
