_comment: 'Capacity data fetched from the test payload (capacity is sent in all payloads).
  Parsing for production is done on instantaneous measurements : this is not reliable
  at all'
bounding_box:
  - - 114.94014224400007
    - -32.52536222099991
  - - 116.05219218900004
    - -31.493806526999947
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: 0
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 0
  coal:
    datetime: '2023-01-01'
    source: null
    value: 0
  gas:
    datetime: '2023-01-01'
    source: null
    value: 0
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: 0
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 0
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: 0
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 0
  oil:
    datetime: '2023-01-01'
    source: null
    value: 2.1
  solar:
    datetime: '2023-01-01'
    source: null
    value: 0.6
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: 0.6
contributors:
  - ajoga
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 292.8252892705995
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 292.8252892705995
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 475.16042054489543
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 475.16042054489543
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.7214348874672578
        solar: 0.09655515040514011
        unknown: 0.0
        wind: 0.18206372128287882
parsers:
  production: ajenti.fetch_production
timezone: Australia/Perth
