bounding_box:
  - - 140.46708580936263
    - -39.64495208099984
  - - 150.47207507627593
    - -33.486452325214685
bypassedSubZones:
  - AU-LH
  - AU-TAS-CBI
  - AU-WA-RI
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 157.2
  biomass:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 384.1
  coal:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 18359
  gas:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 8488.4
  geothermal:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 0
  hydro:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 5745
  hydro storage:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 1320
  nuclear:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 0
  oil:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 1389.2
  solar:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 19988.2
  unknown:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: null
  wind:
    datetime: '2023-01-01'
    source: opennem.org.au
    value: 7173.8
contributors:
  - corradio
  - unitrium
  - MariusKroon
  - chuqtas
  - jarek
  - ajoga
  - brandongalbraith
estimation_method: RECONSTRUCT_BREAKDOWN
subZoneNames:
  - AU-LH
  - AU-NSW
  - AU-NT
  - AU-QLD
  - AU-SA
  - AU-TAS
  - AU-TAS-CBI
  - AU-TAS-FI
  - AU-TAS-KI
  - AU-VIC
  - AU-WA
  - AU-WA-RI
timezone: Australia/Sydney
