bounding_box:
  - - -74.5185401854018
    - -34.24045114057622
  - - -34.29614796147959
    - 5.766573637368978
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: ons.org.br
    value: null
  biomass:
    datetime: '2023-01-01'
    source: ons.org.br
    value: null
  coal:
    datetime: '2023-01-01'
    source: ons.org.br
    value: null
  gas:
    datetime: '2023-01-01'
    source: ons.org.br
    value: null
  geothermal:
    datetime: '2023-01-01'
    source: ons.org.br
    value: null
  hydro:
    datetime: '2023-01-01'
    source: ons.org.br
    value: 109413
  hydro storage:
    datetime: '2023-01-01'
    source: ons.org.br
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: ons.org.br
    value: 1990
  oil:
    datetime: '2023-01-01'
    source: ons.org.br
    value: null
  solar:
    datetime: '2023-01-01'
    source: ons.org.br
    value: 30431
  unknown:
    datetime: '2023-01-01'
    source: ons.org.br
    value: 39584
  wind:
    datetime: '2023-01-01'
    source: ons.org.br
    value: 25628
contributors:
  - alexanmtz
  - corradio
  - systemcatch
  - nessie2013
  - VIKTORVAV99
estimation_method: RECONSTRUCT_BREAKDOWN
subZoneNames:
  - BR-CS
  - BR-N
  - BR-NE
  - BR-S
