_comment: Coal capacity is 0MW after decomissioning of Selkirk in April 2021 (not
  reflected in latest report from March 2021)
bounding_box:
  - - -102.50159786704786
    - 48.492669576869844
  - - -88.44699962056833
    - 60.500059011375754
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: null
  coal:
    datetime: '2023-01-01'
    source: null
    value: 0
  gas:
    datetime: '2023-01-01'
    source: null
    value: 237
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: null
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 5234
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: null
  oil:
    datetime: '2023-01-01'
    source: null
    value: 13
  solar:
    datetime: '2023-01-01'
    source: null
    value: null
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: 258
contributors:
  - felixvanoost
fallbackZoneMixes:
  _source: Statistics Canada - average production in 2020
  _url: https://docs.google.com/spreadsheets/d/1gobOiDRBsxKEKQPG2x5o2Qx17bQLXTSJLtF1JeasKWI/edit?usp=sharing
  powerOriginRatios:
    value:
      gas: 0.003
      hydro: 0.9715
      wind: 0.0254
timezone: America/Winnipeg
