bounding_box:
  - - -109.95372473899994
    - -27.701429945999905
  - - -104.95954342399995
    - -25.95549895599993
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: null
  coal:
    datetime: '2023-01-01'
    source: null
    value: null
  gas:
    datetime: '2023-01-01'
    source: null
    value: null
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: null
  hydro:
    datetime: '2023-01-01'
    source: null
    value: null
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: null
  oil:
    datetime: '2023-01-01'
    source: null
    value: 8.05
  solar:
    datetime: '2023-01-01'
    source: null
    value: 0.128
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: null
contributors:
  - autipial
timezone: Pacific/Easter
