bounding_box:
  - - -5.887418011072289
    - 35.37135845199824
  - - -4.778463534102098
    - 36.42262502599443
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: ree.es
    value: null
  biomass:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
  coal:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
  gas:
    datetime: '2023-01-01'
    source: ree.es
    value: 13
  geothermal:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
  hydro:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
  hydro storage:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
  nuclear:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
  oil:
    datetime: '2023-01-01'
    source: ree.es
    value: 78
  solar:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
  unknown:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
  wind:
    datetime: '2023-01-01'
    source: ree.es
    value: 0
contributors:
  - VIKTORVAV99
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
  productionCapacity: REE.fetch_production_capacity
timezone: Europe/Madrid
