bounding_box:
  - - 4.2302808850321
    - 42.982043008785
  - - 7.7169378581589
    - 45.12684420383
capacity:
  biomass: 293
  hydro: 3269
  nuclear: 0
  solar: 1334
  unknown: 3283
  wind: 48
contributors:
  - https://github.com/AilinvandenHonigkuchenpferdlande
parsers:
  production: ECO2MIX.fetch_production
timezone: Europe/Paris
