bounding_box:
  - - -54.708003
    - 2.10212
  - - -51.595232
    - 5.78601
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: IRENA.org
    value: null
  biomass:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 1.976
  coal:
    datetime: '2023-01-01'
    source: IRENA.org
    value: null
  gas:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 80
  geothermal:
    datetime: '2023-01-01'
    source: IRENA.org
    value: null
  hydro:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 119.13
  hydro storage:
    datetime: '2023-01-01'
    source: IRENA.org
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: IRENA.org
    value: null
  oil:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 108
  solar:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 44.879
  unknown:
    datetime: '2023-01-01'
    source: IRENA.org
    value: null
  wind:
    datetime: '2023-01-01'
    source: IRENA.org
    value: null
contributors:
  - PETILLON-Sebastien
  - VIKTORVAV99
parsers:
  price: FR_O.fetch_price
  production: FR_O.fetch_production
  productionCapacity: IRENA.fetch_production_capacity
timezone: Europe/Paris
