bounding_box:
  - - 67.434082
    - 11.393879
  - - 100.327148
    - 27.664069
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 513.24
  coal:
    datetime: '2023-01-01'
    source: null
    value: 35887.0
  gas:
    datetime: '2023-01-01'
    source: null
    value: 80.0
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: null
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 6331.74
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 0
  oil:
    datetime: '2023-01-01'
    source: null
    value: 92.71
  solar:
    datetime: '2023-01-01'
    source: null
    value: 917.72
  unknown:
    datetime: '2023-01-01'
    source: null
    value: 0
  wind:
    datetime: '2023-01-01'
    source: null
    value: 0
contributors:
  - unitrium
parsers:
  consumption: IN.fetch_consumption
  production: IN.fetch_production
timezone: Asia/Kolkata
