bounding_box:
  - - 62.775879
    - 6.031311
  - - 95.668945
    - 22.755921
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 3734.75
  coal:
    datetime: '2023-01-01'
    source: null
    value: 43397.5
  gas:
    datetime: '2023-01-01'
    source: null
    value: 6491.8
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: null
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 13670.43
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 3320.0
  oil:
    datetime: '2023-01-01'
    source: null
    value: 460.49
  solar:
    datetime: '2023-01-01'
    source: null
    value: 25044.86
  unknown:
    datetime: '2023-01-01'
    source: null
    value: 0
  wind:
    datetime: '2023-01-01'
    source: null
    value: 19655.72
contributors:
  - hectorespert
  - gopikrishna1793
  - unitrium
emissionFactors:
  direct:
    unknown:
      - datetime: '2020-01-01'
        source: CEA 2022; assumes 56% biomass, 36% hydro, 8% unknown
        value: 45
  lifecycle:
    unknown:
      - datetime: '2020-01-01'
        source: CEA 2022; assumes 56% biomass, 36% hydro, 8% unknown
        value: 192
isLowCarbon:
  unknown:
    value: 0.92
isRenewable:
  unknown:
    value: 0.92
parsers:
  consumption: IN.fetch_consumption
  production: IN.fetch_production
timezone: Asia/Kolkata
