bounding_box:
  - - 135.84
    - 33.82
  - - 138.72
    - 37.17
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 352.6
  coal:
    datetime: '2023-01-01'
    source: null
    value: 5170
  gas:
    datetime: '2023-01-01'
    source: null
    value: 14136
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: 2
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 2180
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: 3320
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 3617
  oil:
    datetime: '2023-01-01'
    source: null
    value: 2275
  solar:
    datetime: '2023-01-01'
    source: null
    value: 550
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: 210
contributors:
  - tmslaine
  - lorrieq
  - pierresegonne
  - wobniarin
disclaimer: The data provided for solar power production is suspected to be too high
  (source; Chubu Electric Power Co.,Inc.).
emissionFactors:
  lifecycle:
    unknown:
      _comment: 'Source: Derived from 2016-2019 Chubu area supply statistics and 2017-2018
        Chubu Electric report'
      _url:
        - https://www.chuden.co.jp/corporate/publicity/datalist/juyo/dat_kousei/index.html
        - http://denki-yoho.chuden.jp/denki_yoho_content_data/areabalance_current_term.csv
      source: assumes 26.3% coal, 2.2% oil, 62.5% gas, 9% hydro and wind
      value: 538
parsers:
  consumptionForecast: JP.fetch_consumption_forecast
  price: JP.fetch_price
  production: JP.fetch_production
timezone: Asia/Tokyo
