bounding_box:
  - - 132.15
    - 32.53
  - - 134.69
    - 34.63
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 406
  coal:
    datetime: '2023-01-01'
    source: null
    value: 950
  gas:
    datetime: '2023-01-01'
    source: null
    value: 935
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: 0
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 1153
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: 615
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 890
  oil:
    datetime: '2023-01-01'
    source: null
    value: 1350
  solar:
    datetime: '2023-01-01'
    source: null
    value: 2230
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: 227
contributors:
  - tmslaine
  - lorrieq
  - wobniarin
  - PPsyrius
disclaimer: The data provider (Yonden Shikoku Electric Power Co.,Inc.) provides live
  data only for solar and unknown. We are working on improving the data quality for
  this zone.
emissionFactors:
  lifecycle:
    unknown:
      source: Enerdata 2022 Japanese National Average
      value: 462
parsers:
  consumptionForecast: JP.fetch_consumption_forecast
  price: JP.fetch_price
  production: JP.fetch_production
sources:
  Enerdata 2022 Japanese National Average:
    link: https://www.climate-transparency.org/wp-content/uploads/2022/10/CT2022-Japan-Web.pdf
timezone: Asia/Tokyo
