bounding_box:
  - - 138.5
    - 34.52
  - - 141.16
    - 37.17
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 2847.6
  coal:
    datetime: '2023-01-01'
    source: null
    value: 33620
  gas:
    datetime: '2023-01-01'
    source: null
    value: 92381.7
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: 426.0
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 17215
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: 22052
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 27019
  oil:
    datetime: '2023-01-01'
    source: null
    value: 28579.8
  solar:
    datetime: '2023-01-01'
    source: null
    value: 28577.9
  unknown:
    datetime: '2023-01-01'
    source: null
    value: 9976.9
  wind:
    datetime: '2023-01-01'
    source: null
    value: 3978.8
contributors:
  - kongkille
  - lorrieq
  - tmslaine
  - wobniarin
  - pierresegonne
  - nessie2013
subZoneNames:
  - JP-CB
  - JP-CG
  - JP-HKD
  - JP-HR
  - JP-KN
  - JP-KY
  - JP-ON
  - JP-SK
  - JP-TH
  - JP-TK
timezone: Japan/Tokyo
