bounding_box:
  - - 8.97709477094773
    - 46.557054525418124
  - - 10.081495814958174
    - 47.76313045336413
emissionFactors:
  direct:
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0
  lifecycle:
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490
    oil:
      datetime: '2014-01-01'
      source: EIA 2020/BEIS 2021; IPCC 2014
      value: 650
sources:
  IPCC 2014:
    link: >-
      https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
timezone: Europe/Vaduz
