bounding_box:
  - - 81.37741877418776
    - 6.592635332223807
  - - 82.37741877418776
    - 7.592635332223807
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 0
  biomass:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 50.09
  coal:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 900
  gas:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 0
  geothermal:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 0
  hydro:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 1795
  hydro storage:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 0
  nuclear:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 0
  oil:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 1297.9
  solar:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 422
  unknown:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 0
  wind:
    datetime: '2023-01-01'
    source: IRENA.org
    value: 179
contributors:
  - q--
parsers:
  production: CEB.fetch_production
  productionCapacity: IRENA.fetch_production_capacity
timezone: Asia/Colombo
