bounding_box:
  - - -17.51374332534519
    - 20.919971097581723
  - - -0.5319994709999492
    - 36.426519149000015
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 0
  coal:
    datetime: '2023-01-01'
    source: null
    value: 4116
  gas:
    datetime: '2023-01-01'
    source: null
    value: 1944
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: 0
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 1306
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: 464
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 0
  oil:
    datetime: '2023-01-01'
    source: null
    value: 916
  solar:
    datetime: '2023-01-01'
    source: null
    value: 711
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: 1220
contributors:
  - veqtrus
fallbackZoneMixes:
  _source: https://ourworldindata.org/grapher/electricity-prod-source-stacked?time=earliest..latest&country=~MAR
  powerOriginRatios:
    value:
      coal: 0.4157
      gas: 0.2443
      hydro: 0.0379
      oil: 0.114
      solar: 0.0474
      wind: 0.1409
parsers: {}
timezone: Africa/Casablanca
