bounding_box:
  - - -61.252194
    - 14.364404
  - - -60.732382
    - 14.888562
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 15.082
  coal:
    datetime: '2023-01-01'
    source: null
    value: null
  gas:
    datetime: '2023-01-01'
    source: null
    value: 129
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: 0
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 0
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: null
  oil:
    datetime: '2023-01-01'
    source: null
    value: 292
  solar:
    datetime: '2023-01-01'
    source: null
    value: 53.97
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: 1.1
contributors:
  - PETILLON-Sebastien
  - VIKTORVAV99
parsers:
  price: FR_O.fetch_price
  production: FR_O.fetch_production
timezone: Europe/Paris
