bounding_box:
  - - 166.91871178500003
    - -47.777601820999905
  - - 168.76099694100003
    - -46.18303801899992
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: null
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 0
  coal:
    datetime: '2023-01-01'
    source: null
    value: 0
  gas:
    datetime: '2023-01-01'
    source: null
    value: 0
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: null
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 0
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 0
  oil:
    datetime: '2023-01-01'
    source: null
    value: 1.096
  solar:
    datetime: '2023-01-01'
    source: null
    value: 0
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: 0
contributors:
  - madsnedergaard
timezone: Pacific/Auckland
