bounding_box:
  - - 116.46336963369632
    - 7.323918659865512
  - - 124.9190441904419
    - 19.14290487703049
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: 72
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 175
  coal:
    datetime: '2023-01-01'
    source: null
    value: 8792
  gas:
    datetime: '2023-01-01'
    source: null
    value: 3731
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: null
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 1806
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: 736
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 0
  oil:
    datetime: '2023-01-01'
    source: null
    value: 2357
  solar:
    datetime: '2023-01-01'
    source: null
    value: 960
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: 337
contributors:
  - VIKTORVAV99
  - jarek
  - systemcatch
  - q--
  - mathilde-daugy
  - pierresegonne
  - xomanuel
parsers:
  production: IEMOP.fetch_production
timezone: Asia/Manila
