bounding_box:
  - - 119.31099810998111
    - 4.57480853775256
  - - 127.08266582665826
    - 10.957111072508837
capacity:
  battery storage:
    datetime: '2023-01-01'
    source: null
    value: 49
  biomass:
    datetime: '2023-01-01'
    source: null
    value: 79
  coal:
    datetime: '2023-01-01'
    source: null
    value: 2268
  gas:
    datetime: '2023-01-01'
    source: null
    value: 0
  geothermal:
    datetime: '2023-01-01'
    source: null
    value: null
  hydro:
    datetime: '2023-01-01'
    source: null
    value: 1191
  hydro storage:
    datetime: '2023-01-01'
    source: null
    value: null
  nuclear:
    datetime: '2023-01-01'
    source: null
    value: 0
  oil:
    datetime: '2023-01-01'
    source: null
    value: 833
  solar:
    datetime: '2023-01-01'
    source: null
    value: 84
  unknown:
    datetime: '2023-01-01'
    source: null
    value: null
  wind:
    datetime: '2023-01-01'
    source: null
    value: null
contributors:
  - VIKTORVAV99
  - jarek
  - systemcatch
  - q--
  - mathilde-daugy
  - pierresegonne
  - xomanuel
parsers:
  production: IEMOP.fetch_production
timezone: Asia/Manila
