on:
  workflow_call:
jobs:
  cypress-test:
    name: Cypress tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Playwright
        run: npx playwright install-deps webkit
      - name: Cypress run (old)
        uses: cypress-io/github-action@v4
        env:
          TZ: Europe/Copenhagen
        with:
          working-directory: ./web
          #browser: webkit
          start: yarn run develop
          wait-on: 'http://localhost:8080'
      - name: Cypress run (new)
        uses: cypress-io/github-action@v4
        env:
          TZ: Europe/Copenhagen
        with:
          working-directory: ./web
          #browser: webkit
          build: yarn run build-debug
          start: yarn run server-dev
          wait-on: 'http://localhost:8080'
      - name: Cypress run (old)
        uses: cypress-io/github-action@v4
        env:
          TZ: Europe/Copenhagen
        with:
          working-directory: ./web
          #browser: webkit
          start: yarn run develop
          wait-on: 'http://localhost:8080'