name: End to end test
on: push

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: SNOWPACK_PUBLIC_ELECTRICITYMAP_PUBLIC_TOKEN='${{ secrets.SNOWPACK_PUBLIC_ELECTRICITYMAP_TOKEN }}'
          working-directory: ./web
          start: yarn develop
          wait-on: "http://localhost:8080"
