name: End to end test
on: push
jobs:
  cypress-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        working-directory: ./web
      - name: Cypress run
        uses: cypress-io/github-action@v2
        working-directory: ./web
