name: End to end test
on: push
jobs:
  cypress-test:
    runs-on: ubuntu-20.04
    env:
      API-KEY: ${{ secrets.SNOWPACK_PUBLIC_ELECTRICITYMAP_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          working-directory: ./web
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./web
          start: "SNOWPACK_PUBLIC_ELECTRICITYMAP_TOKEN=$API-KEY yarn develop"
          wait-on: "http://localhost:8080"
