name: End to end test
on: push

env:
  SNOWPACK_PUBLIC_ELECTRICITYMAP_PUBLIC_TOKEN: "${{ secrets.SNOWPACK_DUMMY_TOKEN }}"

jobs:
  cypress-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          working-directory: ./web
      - name: log1
        run: echo ${{ env.SNOWPACK_PUBLIC_ELECTRICITYMAP_PUBLIC_TOKEN }}
      - name: log2
        run: echo ${{ secrets.SNOWPACK_DUMMY_TOKEN }}
      - name: log3
        run: echo hello world
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./web
          start: yarn develop
          wait-on: "http://localhost:8080"
