on:
  workflow_call:
jobs:
  cypress-test:
    name: Cypress tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #- name: Prepare Playwright
      #  run: npx playwright install-deps webkit
      # - name: Cypress run (Safari)
      #   uses: cypress-io/github-action@v4
      #   env:
      #     TZ: Europe/Copenhagen
      #   with:
      #     browser: webkit
      #     working-directory: ./web
      #     start: yarn develop
      #     wait-on: 'http://localhost:8080'
      - name: Build release
        run: yarn run build-debug
      - name: Cypress run (Chrome)
        uses: cypress-io/github-action@v4
        env:
          TZ: Europe/Copenhagen
        with:
          working-directory: ./web
          start: yarn server-dev
          wait-on: 'http://localhost:8080'
